### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mengfankitty** [xiaoxinghu/orgajs#12]
There is an error `ReferenceError: regeneratorRuntime is not defined` when `gatsby develop` with `gatsby: 2.0.37`,  and without any problem on `gatsby: 1.9.277`.

**Comment by xiaoxinghu** [comment]
Yes, the `gatsby-transformer-orga` is not adapting Gatsby 2 yet. I will find time to update it.

**Comment by xiaoxinghu** [comment]
@mengfankitty I have fixed it in a prerelease version, please verify by installing it with `npm i gatsby-transformer-orga@next`, I will release it as stable version when proven it's without any further issues. Please refer to the [starter project](https://github.com/xiaoxinghu/gatsby-orga) as an example if you have trouble migrating your project.

**Comment by xiaoxinghu** [comment]
fixed in the new release, closing this.
