### ISSUE TITLE
Expose meta content for filters

### ISSUE THREAD

**Issue by HaoZeke** [xiaoxinghu/orgajs#13]
# Problem

Currently, `orga` does not support variable graphql queries since only `internal` is exposed.

## Details

For `remark` this is valid:

```graphql
allMarkdownRemark(
      filter: { frontmatter: { category: { in: ["Pandas"] } } }
    ) {
      totalCount
      edges {
        node {
          frontmatter {
            title
            category
            date
          }
        }
      }
    }
}
```

However, the only option for filtering `orga` is `allOrga (
    filter: { internal: {content: { regex: "/CATEGORY:/"}}} 
  )`

Since currently `query CategoryPage($category: String) { (
    filter: { internal: {content: { regex: "/CATEGORY:/" regex: $category }}} 
  )` also does not work.

## Suggestion

If the `meta` object could be exposed to be similar to the `remark` `frontmatter` object, it would be greatly appreciated.

**Comment by xiaoxinghu** [comment]
The `gatsby-transformer-orga` package received a pretty big overhaul. New features are added. Please head over to the [doc page](https://xiaoxinghu.github.io/orgajs/docs/generate-static-website-with-gatsby) for details. That resolves your issue by putting all metadata into a `meta` property. I think you will like it. 😉

**Comment by HaoZeke** [comment]
Thanks so much! Works perfectly now, will be transitioning to pure org mode and writing it up!!
