### ISSUE TITLE
[Question] Converting GNU Extended Regular Expressions to PRE

### ISSUE THREAD

**Issue by ngortheone** [xiaoxinghu/orgajs#17]
Hi @xiaoxinghu 

I am starting to work on the similar project, but in Rust. I stumbled upon your project and I was very happy to learn that I am not the only one crazy about org-mode.

The first thing I learned is that emacs uses different version of regexps (namely [GNU ERE](https://www.regular-expressions.info/gnu.html#ere) while all normal programming languages use Perl Compatible Regexps)

I am currently trying to go through https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-element.el trying to write something something similar in Rust.

How did you convert regexps in `org-element-paragraph-separate` and `org-element--object-regexp` to PCRE? Did you use any automatic tools?

Secondly, since you basically did the same job of writing a parser - is there any advice you can share?
It will be my first attempt at writing a parser.

Thanks

**Comment by xiaoxinghu** [comment]
Sorry for the late reply. I wrote all the regex base on the [org-mode syntax page](https://orgmode.org/worg/dev/org-syntax.html). Feels like reinventing wheels but hey, that's what we do ;-).

In terms of advice, I think the most important one is to keep the end goal in mind always. You can write a parser to do syntax highlighting for a text editor, or generate a syntax tree and translate to other forms (like this project). They are totally different things. Don't try to put them together forcibly. I learnt it the hard way.

**Comment by xiaoxinghu** [comment]
Closing since there's no further action.
