### ISSUE TITLE
Should the paragraph lines be joined?

### ISSUE THREAD

**Issue by vidyu** [xiaoxinghu/orgajs#2]
Hi. Really like your work.
I have a question regarding the paragraphs. When I parse the following two strings I become the same result.
``` 
const ast = parse(`
 * This is heading
   This is line one
   This is line two
 `);
```
and 
```
 const ast = parse(`
 * This is heading
   This is line one This is line two
 `);
````
The both produce the same ast:
```
console.log(ast.children[0].children[1].children[0]);
// { type: 'text',
//   children: [],
//   value: 'This is line one This is line two',
//   parent: 
//    { type: 'paragraph',
//      children: [ [Circular] ],
//      parent: { type: 'section', children: [Array], level: 1, parent: [Object] } } }
```
I would expect the value to have newlines for the first example. Maybe my logic is wrong but if we join with newline, instead with space [here](https://github.com/xiaoxinghu/orgajs/blob/31d02db2ff1dc8432f354e4b85b497f80804c79b/packages/orga/src/processors/line.js#L14) it should be okay.
Say if you would like a pull request and have a nice day!

**Comment by xiaoxinghu** [comment]
@vidyu It's actually by design that way. I try to follow the org-mode syntax as close as possible. As mentioned [here](https://orgmode.org/worg/dev/org-syntax.html#Paragraphs):
> Empty lines and other elements end paragraphs.
So in order to separate the second line into it's own paragraph, you need the have a empty line before it. 
This is especially useful when in emacs, you use `org-fill-paragraph` to "prettify" your document, you want the long paragraph to have a max width per line, but you don't want each line to be a separate paragraph when you export it.

**Comment by vidyu** [comment]
Thank you for the quick answer and the info. I'm closing the issue then.

**Comment by alanctkc** [comment]
Ran into this too! I guess it's a downside of using an AST-- it can't _completely_ guarantee you could translate it back into the original text. Was hoping I could back go the other way with it, but this makes sense.

**Comment by alanctkc** [comment]
So, just a thought on this, @xiaoxinghu. Even if you don't create a new paragraph node, wouldn't you still want to preserve the newline in the text? Isn't it part of the text in that paragraph, since it's not separating from the next paragraph by an empty line?

**Comment by xiaoxinghu** [comment]
@alanctkc the newline character (e.g. "\n") is translated into a space, that's also the org-mode export behaviour. People (like me) use `fill-paragraph` constantly to make the raw text clean and readable, but when export, we expect them to be a normal paragraph, separated by spaces.

**Comment by alanctkc** [comment]
Ahhh, didn't realize that was consistent with export too. Disregard, and thanks for the explanation!
