### ISSUE TITLE
Should the term of description list display be bolded?

### ISSUE THREAD

**Issue by wallevy** [xiaoxinghu/orgajs#20]
If I use the description list,

```org
- Term 1 :: description
- Term 2 :: descrition
```

it will be rendering as below:

- Term 1 :: description
- Term 2 :: descrition

Maybe the term name display should be bolded, and just need one colon:

- **Term 1** : description
- **Term 2** : descrition

[Orgmode Description list](https://orgmode.org/manual/Plain-lists.html)

**Comment by xiaoxinghu** [comment]
ok, noted, that syntax is currently not supported yet. Will be working on that later.

**Comment by anicholson** [comment]
Just noticed that today. That'd be a wonderful feature as description lists are one of my favourite distinguishing features from Markdown :)

**Comment by anicholson** [comment]
> Maybe the term name display should be bolded, and just need one colon:

Perhaps it should emit definition-list HTML?

<dl>
  <dt>Term 1</dt>
  <dd>description 1</dd>
  <dt>Term 2</dt>
  <dd>description 2</dd>
</dl>

**Comment by wallevy** [comment]
Yes, if you export html from org file within emacs, the description list will be rendered as:

```html
<dl>
  <dt>Coffee</dt>
  <dd>Black hot drink</dd>
  <dt>Milk</dt>
  <dd>White cold drink</dd>
</dl>
```

and the ordered lists, unordered lists will be `<ol><li></li></ol>` and `<ul><li></li></ul>`.

**Comment by xiaoxinghu** [comment]
@anicholson descriptive list is supported now with version v1.5.0. Please verify, report any issues you encounter.
