### ISSUE TITLE
Table header is not supported

### ISSUE THREAD

**Issue by hjiang** [xiaoxinghu/orgajs#29]
Hi. Thanks for the great work on Orga.

I'm using `gatsby-transformer-orga` for my sites. Today I found that table headers are not supported. For example, the following table: 

```
| A | B |
|---+---|
| 1 | 2 |
```

should translate to:

```html
<table>
  <thead>
    <tr>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
```

But `gatsby-transformer-orga` puts everything in `<table><tbody>...</tbody></table>`.

**Comment by xiaoxinghu** [comment]
fixed in the latest version (v1.5.2).
