### ISSUE TITLE
Rows and offsets

### ISSUE THREAD

**Issue by alanctkc** [xiaoxinghu/orgajs#3]
I'm wondering, since I'd like to be able to use orga to parse text then decorate the original text without modifying it-- would there be some way for orga to keep track of which characters a specific node maps back to in the source text?

So for example, being able to say that row 6, characters 1 - 10, correspond to a `bold` node.

Did you ever attempt to go down that route, or from your perspective do you think it's feasible?

**Comment by xiaoxinghu** [comment]
Sounds like you are building something like a org-mode editor, doing syntax highlighting stuff. I am actually doing similar thing in a swift version of org-mode parser. This library was a direct port of the swift version. Then I quickly found out that the performance was not ideal for syntax highlight. (real time parsing while user is typing). So I created another one optimised for doing just syntax highlight.

For `orgajs`, I think it's not impossible to preserve location information in the final AST. But I doubt it will give you decent performance for real time parsing kind of job. You know lots of org-mode users (me included) sometimes have huge org files. I am not sure myself. My thought on this is also evolving. For now I think there should be two separate parsers for these two jobs (parse -> AST vs. parse -> Syntax Highlight). That's what I am doing in my iOS app right now. One parser to generate AST and generate meaningful data structure for the program to understand and utilise the document, like generating agenda, searching ... Another parser purely for syntax highlight. Don't know anything about the syntax, only recognise patterns and provide a name + location. But they can have shared lexer.

Let me think about the design of `orgajs`, maybe there's something we can do to make it work for both scenarios. Any ideas are welcome.

**Comment by alanctkc** [comment]
That makes sense for sure. What are the main performance bottlenecks for the AST parser?
