### ISSUE TITLE
Performance degrades quickly with line length and line count, possibly line content

### ISSUE THREAD

**Issue by whacked** [xiaoxinghu/orgajs#6]
I noticed that for some files (e.g. > 10k lines) the parser practically cannot complete. This seems to be a function of number of lines and line lengths. For example, a large file with many blank lines can still complete. I don't know if this is specific to orga, or to unifyjs.

Here's a quick test on how the total parsing time for a trivial file changes with the line length, content, and line count:

```javascript
parse = require("orga").parse;

function pad(n, width) {
    n += '';
    return n.length >= width ? n : new Array(width - n.length + 1).join('0') + n;
}

[
    (n) => `_${n}___${n}_`,
    (n) => `(${n})_(${n})`,
    (_) => 'xxxxxx_xxxxxx',
    (_) => 'xxxxxx_xxxxxx######_######',
].forEach(function(templater) {
    for(nlines = 500; nlines <= 5000; nlines += 500) {
        var lines = [
        '* blah\n',
        ];
        for(var n=1;++n<=nlines;) {
            lines.push(templater(pad(n, 4)));
        }
        var text = lines.join('\n');
        var t0 = new Date().getTime();
        var ast = parse(text)
        var tN = new Date().getTime();
        var dt = tN - t0;
        var lastLine = lines[lines.length-1];
        console.log(`|\t${lastLine}\t|\t${nlines}\t|\t${dt}\t|`);
    }
});
```

Plotting the output shows this:

![speedtest](https://user-images.githubusercontent.com/33410/43371052-dfa2b7c8-933e-11e8-96e3-a833aa59d7b8.png)

I was wondering whether the same regex issue was affecting likes w ith `(` and `)` but it seems like that is not the case, but the lines with parens are clearly slower than lines without parens.

This is the table from the script (first column is added afterwards):
```
|under| _0500___0500_              |  500 |   162 |
|under| _1000___1000_              | 1000 |   626 |
|under| _1500___1500_              | 1500 |  1376 |
|under| _2000___2000_              | 2000 |  2474 |
|under| _2500___2500_              | 2500 |  3865 |
|under| _3000___3000_              | 3000 |  5475 |
|under| _3500___3500_              | 3500 |  7521 |
|under| _4000___4000_              | 4000 |  9850 |
|under| _4500___4500_              | 4500 | 12427 |
|under| _5000___5000_              | 5000 | 15190 |
|paren| (0500)_(0500)              |  500 |   217 |
|paren| (1000)_(1000)              | 1000 |   858 |
|paren| (1500)_(1500)              | 1500 |  1955 |
|paren| (2000)_(2000)              | 2000 |  3483 |
|paren| (2500)_(2500)              | 2500 |  5439 |
|paren| (3000)_(3000)              | 3000 |  7850 |
|paren| (3500)_(3500)              | 3500 | 10711 |
|paren| (4000)_(4000)              | 4000 | 13873 |
|paren| (4500)_(4500)              | 4500 | 17560 |
|paren| (5000)_(5000)              | 5000 | 21619 |
|xxxxx| xxxxxx_xxxxxx              |  500 |   215 |
|xxxxx| xxxxxx_xxxxxx              | 1000 |   854 |
|xxxxx| xxxxxx_xxxxxx              | 1500 |  1923 |
|xxxxx| xxxxxx_xxxxxx              | 2000 |  3429 |
|xxxxx| xxxxxx_xxxxxx              | 2500 |  5471 |
|xxxxx| xxxxxx_xxxxxx              | 3000 |  7843 |
|xxxxx| xxxxxx_xxxxxx              | 3500 | 10564 |
|xxxxx| xxxxxx_xxxxxx              | 4000 | 13859 |
|xxxxx| xxxxxx_xxxxxx              | 4500 | 17445 |
|xxxxx| xxxxxx_xxxxxx              | 5000 | 21576 |
|xand#| xxxxxx_xxxxxx######_###### |  500 |   815 |
|xand#| xxxxxx_xxxxxx######_###### | 1000 |  3211 |
|xand#| xxxxxx_xxxxxx######_###### | 1500 |  7253 |
|xand#| xxxxxx_xxxxxx######_###### | 2000 | 12967 |
|xand#| xxxxxx_xxxxxx######_###### | 2500 | 20093 |
|xand#| xxxxxx_xxxxxx######_###### | 3000 | 28973 |
|xand#| xxxxxx_xxxxxx######_###### | 3500 | 39765 |
|xand#| xxxxxx_xxxxxx######_###### | 4000 | 51717 |
|xand#| xxxxxx_xxxxxx######_###### | 4500 | 65081 |
|xand#| xxxxxx_xxxxxx######_###### | 5000 | 80055 |
```

Is there an easy way to fix this?

**Comment by whacked** [comment]
Parsing an example string such as

```javascript
var content = `* blah

xxxxxx
xxxxxx
xxxxxx
xxxxxx
...
```

running `parse(content + "\n" + content + "\n" + content);` gives this profiler output:

![screenshot 4](https://user-images.githubusercontent.com/33410/43371249-bdb18c30-9342-11e8-82ab-84f58da85bdc.png)

**Comment by xiaoxinghu** [comment]
Thanks for the impressive analysis, they are super useful. Yes, performance was never the focus up to now, I know there will be issues when the file gets big, because I have similar experiences in my `swift` version. I have a couple of ideas for fixing it, but it will take some time. Regex is convenient, very good for a quick implementation, but it's not performant in some cases. The heavy regex matching in your screenshots are inline format parsing (e.g. bold, italic, links ...). I won't put quick bandaids on it now, I think I need to do it properly. I will add proper performance tests and try to replace the heavy regex with faster solutions.

**Comment by xiaoxinghu** [comment]
@whacked Sorry for the delay of this issue. I was thinking recently, the cause of this issue is probably due to the inline parsing is happening cross multiple lines, so if you have a huge `paragraph`, the regex perf is going to be slaughtered. New lines (empty lines) are considered breaker of the paragraph, that's why huge files full of empty lines are ok. Maybe it makes sense to only do inline parsing within each line. I was looking around, non of the markdown parsers, or even markdown apps, do cross-line parsing. Even org-mode itself only support inline syntax within 3 lines. If I change the parse to not do multiline parsing, What do you think? That means you have to keep them all in one line, if you use `fill-paragraph` in emacs to tidy things up, it will sometimes break long syntax into multiple lines, happen often for links. Is it acceptable?

**Comment by whacked** [comment]
Thanks for the update! I think that's generally reasonable. 2 of the other org parsers that I have played with, https://github.com/mooz/org-js/ and https://github.com/daitangio/org-mode-parser also assume single-line parsers at the bottom of the parser hierarchy. I think users who need multiple lines will compromise by using long lines or repeat the markup across several lines.

On the topic of regexes, one issue which also affects inline parsers (as used in the other 2 libraries mentioned here) is that they cannot handle nested markup, such as `/_italicized bold_/` or `*=bolded code=*` (while `=*asterisk code*=` does not render bold). A stack based parser can handle that, but I don't know how well it fits into orga's architecture.

FWIW I have been running a fork of orga using a modified inline parser like the one in #7 for a while. I think it's ~3x faster, so it still chokes on inputs over e.g. 10k lines. I don't know how easy it is to preserve nested parsing capability and speed.

**Comment by xiaoxinghu** [comment]
@whacked I have just removed multiline support for inline parsing ([commit](https://github.com/xiaoxinghu/orgajs/commit/15a4b337b3995b5c224345b4620d1fddd0b4fdb1)). Please verify if it improves the performance (with the release of v1.1.0). Also, there's an overhaul for `gatsby-transformer-orga` which will probably break your gatsby project. But it adds lots of useful features. [Check it out](https://xiaoxinghu.github.io/orgajs/docs/generate-static-website-with-gatsby) if you use gatsby.

**Comment by whacked** [comment]
I did not do anything extensive, but rerunning the script in this issue yields a 20x~1000x speedup. I will report anything interesting as I update to the new version. Thanks a lot for your work!

**Comment by GuiltyDolphin** [comment]
Thanks for this @whacked!

2021-07-18T13:20 re-run with #104 which supports multiline inline parsing.

Only run up to 3000 because there's a recursion bug I need to fix, but otherwise seems okay. TODO need to compare to current master.

```
|  _0500___0500_               |  500   |  131   |
|  _1000___1000_               |  1000  |  263   |
|  _1500___1500_               |  1500  |  433   |
|  _2000___2000_               |  2000  |  619   |
|  _2500___2500_               |  2500  |  852   |
|  _3000___3000_               |  3000  |  1104  |
|  (0500)_(0500)               |  500   |  93    |
|  (1000)_(1000)               |  1000  |  214   |
|  (1500)_(1500)               |  1500  |  376   |
|  (2000)_(2000)               |  2000  |  556   |
|  (2500)_(2500)               |  2500  |  772   |
|  (3000)_(3000)               |  3000  |  958   |
|  xxxxxx_xxxxxx               |  500   |  83    |
|  xxxxxx_xxxxxx               |  1000  |  197   |
|  xxxxxx_xxxxxx               |  1500  |  337   |
|  xxxxxx_xxxxxx               |  2000  |  521   |
|  xxxxxx_xxxxxx               |  2500  |  788   |
|  xxxxxx_xxxxxx               |  3000  |  1043  |
|  xxxxxx_xxxxxx######_######  |  500   |  167   |
|  xxxxxx_xxxxxx######_######  |  1000  |  475   |
|  xxxxxx_xxxxxx######_######  |  1500  |  653   |
|  xxxxxx_xxxxxx######_######  |  2000  |  956   |
|  xxxxxx_xxxxxx######_######  |  2500  |  1343  |
|  xxxxxx_xxxxxx######_######  |  3000  |  1788  |
```
